#!/usr/bin/env python3

# Script Name:                  Ops Challenge: Python Requests Library
# Author:                       Wayne Brandon
# Date of latest revision:      06/14/2023
# Purpose:                      Educatioal - Learning to work Python Requests Library



import requests
import json

# prompt user for input
url = input('https//api.github.com: ')

# prompt user for http method
method = input('Please select a HTTP method (GET, POST, PUT, DELETE, HEAD, PATCH, OPTIONS): ')

# print to the screen the entire request to send
print('Your script is about to send a ' + method + ' request to ' + url)
confirmation = input('Do you want to continue (Y/N): ')

# handle confirmation
if confirmation.upper() == 'Y':
    response = requests.request(method, url)
    print('Status Code: ' + str(response.status_code))
    if response.status_code == 200:
        print('Site Found')
    elif response.status_code == 404:
        print('Site Not Found')
else:
    print('Cancelling request')

# print response header information to the screen
print(json.dumps(dict(response.headers), indent=4))
